version: "3"
services:
  ticket:
    image: alexeymrvz/ticket
    build:
      context: .
      dockerfile: Dockerfile.ticket-service
    environment:
      PORT: "8070"
    ports:
      - "8070:8070"

  flight:
    image: alexeymrvz/flight
    build:
      context: .
      dockerfile: Dockerfile.flight-service
    environment:
      PORT: "8060"
    ports:
      - "8060:8060"

  bonus:
    image: alexeymrvz/bonus
    build:
      context: .
      dockerfile: Dockerfile.bonus-service
    environment:
      PORT: "8050"
    ports:
      - "8050:8050"

  gateway:
    image: alexeymrvz/gateway
    build:
      context: .
      dockerfile: Dockerfile.gateway-service
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      - ticket
      - flight
      - bonus

volumes:
  db-data:
