name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]

env:
  K8S_TOKEN: ${{ secrets.K8S_TOKEN }}
  K8S_URL: ${{ secrets.K8S_URL }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build the stack
        run: docker-compose build
      
      - name: Push the stack
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker-compose push

      - name: k8s deploy
        run: |
          kubectl config set-cluster lab4-klaster --server="$K8S_URL" --insecure-skip-tls-verify=true
          kubectl config set-credentials admin --token="$K8S_TOKEN"
          kubectl config set-context default --cluster=lab4-klaster --user=admin
          kubectl config use-context default
          kubectl apply -f k8s.yml

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
